version: '3.8'

services:
  app:
    image: toan1762003/server:latest
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://mongo:27017/ServerChronark
      - SECRET_KEY=secret
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongo_data: